{{- $T := . }}
openapi: 3.0.0
info:
  description: "{{ $T.Config.Description }}"
  version: "{{ $T.Config.Version }}"
  title: "{{ $T.Config.Title }}"
{{- if $T.IsBearer }}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
{{- end}}
{{- if $T.IsBasic }}
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
{{- end}}
{{- if $T.IsApiKey }}
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Keay
security:
  - apiKeyAuth: []
{{- end}}
servers:
  - url: "{{ .Config.BasePath }}"
tags:
{{ range $_, $e := $T.SortedEntities }}
- name: "{{ $e.Group }}"
  description: ""
{{ end }}
paths:
{{- range $_, $e := $T.SortedEntities }}
{{- range $path, $resources := $e.Entity }}
  {{ $path | RemovePathPrefixAndReplaceParams }}:
    {{- range $_, $resource := $resources }}
    {{ $resource.Method | ToLower }}:
      tags:
      - "{{ $e.Group }}"
      summary: "{{ $resource.Name }}"
      description: "{{ $resource.Description | UnescapeHTML }}"
      {{- if or $resource.Parameters $resource.Body.Params $resource.Headers $resource.Body.MimeType }}
      {{- if eq $resource.Body.MimeType "multipart/form-data" }}
      {{- if $resource.Body.Params }}
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
               {{- range $_, $pp := $resource.Body.Params }}
               {{ $pp.Name }}:
                type: "string"
                description: "{{ $pp.Description }}"
                {{- if $pp.Type }}
                format: binary
                {{- end }}
               {{- end }}
      {{- end }}
      {{- end }}
      parameters:
      {{- if eq $resource.Body.MimeType "multipart/form-data" }}
      - name: "Content-Type"
        in: "header"
        schema:
          default: "multipart/form-data"
          type: "string"
        required: true
        description: ""
      {{- end }}
      {{- range $_, $pp := $resource.GetPathParams $path }}
      - name: "{{ $pp.Name }}"
        in: "path"
        schema:
          type: "string"
        description: "{{ $pp.Description }}"
        required: true
      {{- end }}
      {{- if eq $resource.Body.MimeType "application/json" }}
      - name: "body"
        in: "body"
        schema:
          default: ""
          type: "string"
        description: "request body"
        required: true
      {{- end }}
      {{- range $p, $param := $resource.Parameters}}
      {{- if $param.IsPathParam $path }}{{- else }}
      - name: "{{ $param.Name }}"
        in: "query"
        schema:
          default: {{- if $param.Disabled }} "" {{- else }} "{{ $param.Value }}" {{- end }}
          type: "string"
        description: "{{ $param.Description }}"
        required: false
      {{- end }}
      {{- end }}
      {{- range $p, $param := $resource.Headers}}
      - name: "{{ $param.Name }}"
        in: "header"
        schema:
          default: ""
          type: "string"
        description: ""
        required: true
      {{- end }}
      {{- end }}
      responses:
        200:
          description: "successful operation"
        204:
          description: "successful operation with nothing to return"
        {{- if $resource.IsWrite }}
        400:
          description: "invalid request data or format"
        {{- end }}
        {{- if $resource.Authentication.Token }}
        {{- if or $T.IsBearer $T.IsApiKey }}
        401:
          description: "missing or invalid authentication token"
        {{- end }}
        {{- end }}
        {{- if $resource.Authentication.Type }}
        {{- if or $T.IsBearer $T.IsApiKey $T.IsBasic }}
        403:
          description: "insuffecient or invalid permissions"
        {{- end }}
        {{- end }}
        404:
          description: "endpoint or resource not found"
    {{- end }}
{{- end }}
{{- end }}
